# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

export PATH=$HOME/bin:/usr/local/bin:/{{ discos_sw_dir }}/introots/default/user/bin:$PATH
export LD_LIBRARY_PATH=/{{ discos_sw_dir }}/introots/default/lib:$LD_LIBRARY_PATH
