# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific aliases and functions
if [ ! -L $HOME/schedules ]; then
    if [ -d /archive/schedules/$USER ]; then
        ln -sfn /archive/schedules/$USER schedules
    fi
fi

if [ ! -L $HOME/data ]; then
    if [ -d /archive/data/$USER ]; then
        ln -sfn /archive/data/$USER data
    fi
fi

if [ ! -L $HOME/extraData ]; then
    if [ -d /archive/extraData/$USER ]; then
        ln -sfn /archive/extraData/$USER extraData
    fi
fi

if [ ! -L $HOME/logs ]; then
    ln -sfn /archive/logs logs
fi

{% if inventory_dir.split('/')[-1] == 'srt' %}
# Temporary solution for sardara not being lustre-integrated
if [ ! -L $HOME/sardaraData ]; then
    ln -sfn /roach2_nuraghe/data/$USER sardaraData
fi
{% endif %}
