# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$HOME/bin:/usr/local/bin:/discos/introots/default/user/bin:$PATH
export PATH

LD_LIBRARY_PATH=/discos/introots/default/lib
export LD_LIBRARY_PATH
