#!/usr/bin/env python
import subprocess
import os
import sys
import argparse
try:
    from urllib.request import urlopen, Request
except ImportError:
    from urllib2 import urlopen, Request
import json


parser = argparse.ArgumentParser()
group = parser.add_mutually_exclusive_group(required=True)
group.add_argument(
    '-b',
    '--branch',
    nargs='?',
    const='stable'
)
group.add_argument('-t', '--tag')
args = parser.parse_args()

choices_type = ''
if args.branch:
    choices_type = 'branches'
    args.target = args.branch
elif args.tag:
    choices_type = 'tags'
    args.target = args.tag

request = Request(
    'https://api.github.com/repos/discos/basie/%s' % choices_type
)
choices = json.loads(urlopen(request).read())
choices = [str(c.get('name')) for c in choices]

if args.target not in choices:
    msg = "ERROR: %s %s not found in remote repository!\nChoose between '%s'."
    if args.branch:
        msg = msg % ('branch', args.target, "', '".join(choices))
    elif args.tag:
        msg = msg % ('tag', args.target, "', '".join(choices))
    print(msg)
    sys.exit(1)

if os.geteuid() != 0:
    os.execvp('sudo', ['sudo', 'python2.7'] + sys.argv)

env_path = '{{ git_dir }}/bin'
if os.environ.get('PATH'):
    env_path += ':%s' % os.environ.get('PATH')
os.environ['PATH'] = env_path

def become_discos():
    def set_ids():
        os.setgid({{ acs_gid }})
        os.setuid({{ user_uid }})
    return set_ids

current_dir = os.path.dirname(os.path.realpath(__file__))
basie_repo = 'basie'
basie_bin_dir = os.path.join(current_dir, 'bin')
basie_repo_dir = os.path.join(current_dir, basie_repo)
basie_repo_url = 'https://github.com/discos/%s.git' % basie_repo

subprocess.call(['rm', '-rf', basie_repo_dir])
subprocess.call(
    ['git',
    'clone',
    basie_repo_url,
    '--branch',
    args.target,
    '--single-branch'],
    cwd=current_dir,
    preexec_fn=become_discos()
)

subprocess.call(
    ['pip2.7',
    'install',
    '-r',
    'requirements.txt'],
    cwd=basie_repo_dir,
)

subprocess.call(
    ['python2.7',
    'setup.py',
    'install',
    '--install-scripts=%s' % basie_bin_dir],
    cwd=basie_repo_dir
)

correction = \
"""import os
import sys

if os.environ.get('LD_LIBRARY_PATH'):
    del os.environ['LD_LIBRARY_PATH']
    os.execvp('/usr/bin/python2.7', ['python2.7'] + sys.argv)
"""

lines = []
for line in open(os.path.join(basie_bin_dir, 'basie')):
    lines.append(line)
    if '#coding=utf-8' in line:
        lines.append(correction)

with open(os.path.join(basie_bin_dir, 'basie'), 'w') as f:
    f.writelines(lines)

subprocess.call([
    'cp',
    os.path.join(basie_bin_dir, 'basie'),
    os.path.join('/usr/bin/', 'basie')
])

subprocess.call(['rm', '-rf', basie_bin_dir])
