#!/bin/sh
#. /etc/rc.d/init.d/functions
#. /etc/sysconfig/network

APP_PATH=/{{ discos_sw_dir }}/sdtools/quicklook/conf

start() {
    cd $APP_PATH
    zdaemon -C service.conf start
}

stop() {
    cd $APP_PATH
    zdaemon -C service.conf stop
}

check_status() {
    cd $APP_PATH
    zdaemon -C service.conf status
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        check_status
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
        RETVAL=2

esac
exit $RETVAL
