#!/usr/bin/env python
from __future__ import print_function
import os

BRANCH_ROOT = os.environ['HOME']
BRANCH_LIST = os.path.join(BRANCH_ROOT, '.discos/branches')


discos_branch = os.environ['DISCOS_BRANCH']

# Remove unavailable branches from the list
branches = []
for line in open(BRANCH_LIST, 'r'):
    branch = line.strip()
    if os.path.exists(os.path.join(BRANCH_ROOT, branch)):
        branches.append(branch)
    lines = [b + '\n' for b in branches]
    open(BRANCH_LIST, 'w').writelines(lines)

if discos_branch:
    active_branch = os.path.join(BRANCH_ROOT, discos_branch)
    if not os.path.exists(active_branch):
        # Clear the the DISCOS_BRANCH environment variable
        lines = []
        load_branch = os.path.join(BRANCH_ROOT, '.discos/load_branch')
        for line in open(load_branch):
            if 'export DISCOS_BRANCH=' in line:
                lines.append('export DISCOS_BRANCH=\n')
            elif 'export CDB=' in line:
                lines.append('export CDB=\n')
            else:
                lines.append(line)
        open(load_branch, 'w').writelines(lines)
    elif active_branch in os.getcwd():
        pass
    else:
        # In case we are in a not active branch, emit a warning
        for branch in branches:
            if os.path.join(BRANCH_ROOT, branch) in os.getcwd():
                print("you are in '%s', but the active "
                      "branch is '%s'" % (branch, discos_branch))
                break
