#!/usr/bin/env python
from __future__ import print_function
import os

BRANCH_ROOT = os.path.join('/home', 'discos')
BRANCH_LIST = '/home/discos/.discos/branches'

discos_branch = os.environ['DISCOS_BRANCH']
if discos_branch:
    active_branch = os.path.join(BRANCH_ROOT, discos_branch)
    if not os.path.exists(active_branch):
        # Clear the the DISCOS_BRANCH environment variable
        lines = []
        load_branch = '{{ discosconf_dir }}/load_branch'
        for line in open(load_branch):
            if 'export DISCOS_BRANCH=' in line:
                lines.append('export DISCOS_BRANCH=\n')
            elif 'export CDB=' in line:
                lines.append('export CDB=\n')
            else:
                lines.append(line)
        open(load_branch, 'w').writelines(lines)
    elif active_branch in os.getcwd():
        pass
    else:
        # In case we are in a not active branch, emit a warning
        with open(BRANCH_LIST, 'r') as f:
            declared_branches = [b.strip() for b in f.readlines()]
            declared_branches.remove(discos_branch)

        for branch in declared_branches:
            if os.path.join(BRANCH_ROOT, branch) in os.getcwd():
                print("you are in '%s', but the active "
                      "branch is '%s'" % (branch, discos_branch))
                break
