#!/usr/bin/env python
from __future__ import print_function
import sys
import os

BRANCH_ROOT = os.path.join('/home', 'discos')
BRANCH_LIST = '/home/discos/.discos/branches'

discos_branch = os.environ['DISCOS_BRANCH']
if not discos_branch:
    sys.exit(0)
else:
    active_branch = os.path.join(BRANCH_ROOT, discos_branch)
    if active_branch in os.getcwd():
        sys.exit(0)
    else:
        # In case we are in a not active branch, emit a warning
        with open(BRANCH_LIST, 'r') as f:
            declared_branches = [b.strip() for b in f.readlines()]
            declared_branches.remove(discos_branch)

        for branch in declared_branches:
            if os.path.join(BRANCH_ROOT, branch) in os.getcwd():
                print("you are in '%s', but the active "
                      "branch is '%s'" % (branch, discos_branch))
                break
