#!/usr/bin/env bash

source {{ acsconf_dir }}/.bash_profile.acs


if [ -z "$INTROOT" ]; then
	export INTROOT={{ introot }}
fi
if [ -z "$STATION" ]; then
	export STATION={{ cdb }}
fi
if [ -z "$ACS_CDB" ]; then
	export ACS_CDB={{ discos_dir }}/{{ cdb }}/Configuration
fi


export PATH=/usr/local/qt/bin/:$PATH
export QTDIR=/usr/local/qt
export QTLIB=$QTDIR/lib
export QTINC=$QTDIR/include
export qt_prefix=$QTLIB
export PATH=$PATH:$QTDIR/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

{% if ansible_hostname != "manager" %}
MNG_IP={{ hostvars[groups['manager'].0].ansible_ssh_host }}
export MANAGER_REFERENCE=corbaloc::$MNG_IP:3000/Manager
{% endif %}
