#!/usr/bin/env bash

export INTROOT={{ introot }}
export STATION={{ station }}

if [[ $CDB = "test" ]]
then
    export ACS_CDB={{ branch_path }}/{{ station }}
else
    export ACS_CDB={{ branch_path }}/{{ station }}/Configuration
fi
