#! /usr/bin/env bash

export DISCOS_BRANCH=
export CDB=
BRANCHENV=/home/{{ user }}/$DISCOS_BRANCH/.branchenv


# Load DISCOS definitions
# =======================
if [ -n "${DISCOS_BRANCH}" ] && [ -f "$BRANCHENV" ]
then
    source $BRANCHENV
fi
