#!/bin/bash

if [[ $(lnetctl net show --net tcp0 | wc -l) -eq 0 ]]; then
    echo -n "Configuring {{ lustre_network_interface }} network interface for lustre..."
    lnetctl lnet configure
    lnetctl net add --net tcp0 --if {{ lustre_network_interface }}
    echo "done."
fi

if [[ $(mount | grep '{{ lustre_server_ip }}@tcp0:/discos' | wc -l) -eq 0 ]]; then
    if [[ $(ping -I {{ lustre_network_interface }} -c 1 -w 1 {{ lustre_server_ip }} > /dev/null) -eq 0 ]]; then
        echo -n "Mounting remote lustre partition..."
        mount -t lustre {{ lustre_server_ip }}@tcp0:/discos /archive
        echo "done."
    else
        echo "Remote lustre server unreachable."
    fi
fi
