syntax enable
colorscheme ron
set number
filetype on  " enables filetype detection
filetype plugin indent on

set ai ts=4 sts=4 et sw=4
autocmd FileType python set ai ts=4 sts=4 et sw=4 tw=79
autocmd FileType rst set ai ts=4 sts=4 et sw=4 tw=79

set backspace=2
set nobackup
imap { {}<esc>i
map <C-n> :tabn<CR>
map <C-p> :tabp<CR>
set updatetime=500
set wmh=0
set hls "highlits of words to search
