#!/bin/bash
# Configuration script for the DISCOS firewall

echo "Firewalling..."

iptables -F
iptables -F --table nat
iptables -X
iptables -X --table nat
iptables -P INPUT DROP
iptables -P OUTPUT ACCEPT
iptables -P FORWARD DROP
iptables -A INPUT -i lo -p all -j ACCEPT
iptables -A OUTPUT -o lo -p all -j ACCEPT
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT
{% if firewall_rules is defined %}
# Machine specific rules
{% for rule in firewall_rules %}
iptables {{ rule }}
{% endfor %}
{% endif %}

iptables-save > /etc/sysconfig/iptables

echo "Done"

echo "Restarting service..."
service iptables restart
echo "End!"
