#!/usr/bin/env bash

# Set the STATION
# ===============
if [ -f /{{ discos_sw_dir }}/config/misc/station ]; then
    source /{{ discos_sw_dir }}/config/misc/station
else
    unset STATION
fi

# Variables to export
# ===================
export QTDIR=/usr/local/{{ qt_version }}
export QTLIB=$QTDIR/lib
export QTINC=$QTDIR/include
export qt_prefix=$QTLIB
export PATH=$PATH:$QTDIR/bin:$HOME/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/lib64:$QTLIB
export PYTHONSTARTUP=$HOME/.pyrc
export EDITOR=vi

# Load the environment at login
# =============================
$PROMPT_COMMAND
{% if inventory_hostname not in groups['manager'] %}

# ACS Manager reference
# =====================
MNG_IP={{ hostvars[groups['manager'].0].ansible_host }}
export MANAGER_REFERENCE=corbaloc::$MNG_IP:3000/Manager
{% endif %}
