#! /usr/bin/env bash

export INTROOT=
export STATION=
export DISCOS_BRANCH=
export CDB=

# Load DISCOS definitions
# =======================
if [ -n "${DISCOS_BRANCH}" ]; then
    if [ $CDB = "test" ]; then
        export ACS_CDB=/discos/{{ user }}/$DISCOS_BRANCH/$STATION
    else
        export ACS_CDB=/discos/{{ user }}/$DISCOS_BRANCH/$STATION/Configuration
    fi
fi
