#!/bin/bash

WINDOW_ID=$(xdotool getactivewindow)

if [[ "$(xdotool getwindowname $WINDOW_ID)" == "x-nautilus-desktop" ]]; then
    exit
fi

DISPLAY_WIDTH=$(expr $(echo $(xdotool getdisplaygeometry) | cut -f 1 -d ' ') / 2)
DISPLAY_HEIGHT=$(echo $(xdotool getdisplaygeometry) | cut -f 2 -d ' ')

xdotool windowmove $WINDOW_ID 0 0
xdotool windowsize $WINDOW_ID $DISPLAY_WIDTH $DISPLAY_HEIGHT
