#!/usr/bin/env python
"""Some command line examples:

  $ discos-login manager
  $ discos-login -u root manager
  $ discos-login -u observer console
"""
from __future__ import print_function
import utils
import subprocess
from argparse import ArgumentParser

utils.checkPython()

parser = ArgumentParser()
parser.add_argument(
    '-u', '--user',
    required=False,
    default='discos'
)
parser.add_argument('machine', choices=utils.machineList())
args = parser.parse_args()

if utils.machineState(args.machine) == 'powered off':
    print('Machine {} is not running.'.format(args.machine))
else:
    subprocess.call([
        'ssh',
        '-X',
        '-l',
        args.user,
        utils.getIp(args.machine)
    ])
