#!/usr/bin/env python
"""Some command line examples:

  $ discos-login manager
  $ discos-login -u root manager
  $ discos-login -u observer console
"""
from __future__ import print_function
import subprocess
from argparse import ArgumentParser
import deployment

parser = ArgumentParser()
parser.add_argument(
    '-u', '--user',
    required=False,
    default='discos'
)
parser.add_argument('machine', choices=deployment.machineList())
args = parser.parse_args()

if deployment.isRunning(args.machine):
    subprocess.call([
        'ssh',
        '-CX',
        '-l',
        args.user,
        deployment.getIp(args.machine)
    ])
else:
    print('Machine {} is not running.'.format(args.machine))
