#!/bin/bash

machine=""
for line in `VBoxManage list vms | awk '{print substr($1, 2, length($1) - 2)}'`
do
    if [[ $line = *"deployment_$1_"* ]]; then
        machine=$line
    fi
done
unset line
if [ "$machine" = "" ]; then
    echo "Machine $1 unrecognized."
    exit 1
fi
state=`VBoxManage showvminfo "$machine" | grep State`
if [[ $state != *"running"* ]]; then
    echo "Machine $1 not running. Please start it by typing 'discos-vms -m $1 start'"
else
    ip=`VBoxManage guestproperty get "$machine" /VirtualBox/GuestInfo/Net/1/V4/IP | awk '{split($0, a); print a[2]}'`
    ssh -X discos@$ip
    unset ip
fi
unset machine
unset state
