#!/bin/bash

start()
{
    sleep 5
    mount -t lustre {{ lustre_server_ip }}@tcp0:/discos /archive || true

    for machine in {{ lustre_clients_list | trim }}; do
        ssh -o ConnectTimeout=5 root@$machine "service lustre start" || true
    done
}

stop()
{
    for machine in {{ lustre_clients_list | trim }}; do
        ssh -o ConnectTimeout=5 root@$machine "service lustre stop" || true
    done

    umount /archive || true
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    *)
        echo $"Usage: $0 {start|stop}"
        RETVAL=2
esac
exit $RETVAL
